name: Build and Deploy React App

on:
  push:
    tags:
      - "*" # triggers on any tag push
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment ?"
        required: true
        type: choice
        options:
          - staging
          - ephemeral

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    environment: ${{ github.event.inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Node setup
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Install, type check, build
      - run: npm ci
      - run: npm run type-check
      - run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_LOCATIONS: ${{ secrets.VITE_API_LOCATIONS }}
          VITE_API_UPLOAD_MEDIA: ${{ secrets.VITE_API_UPLOAD_MEDIA }}

      # Upload build folder for next job
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/

  release:
    needs: ci
    environment: ${{ github.event.inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.REACT_APP_S3_BUCKET }}
      DIST_ID: ${{ secrets.REACT_APP_CLOUDFRONT_ID }}
    steps:
      # Download build folder
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: dist/

      # AWS credentials
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387836084035:role/githubTripWebPlannerApp
          aws-region: eu-central-1
          output-env-credentials: true

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # Sync to S3
      - name: Sync build to S3
        run: aws s3 sync dist/ s3://$BUCKET --delete

      # Invalidate CloudFront
      - name: Invalidate CloudFront cache
        if: env.DIST_ID != ''
        run: aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
